---
- hosts: localhost
  vars:
    user: "cloudru"
    password: "{{ 'cloudpass' | password_hash('sha512') }}"
    sshkey: "{{ lookup('file', '../key/key.pub') }}"
  tasks:
  - name: "Create new user and password"
    user:
      name: "{{ user }}"
      password: "{{ password | password_hash('sha512') }}" 
      create_home: true
      shell: /bin/bash
      append: true
      state: present

  - name: "Copy authorized keys"
    authorized_key:
      user: "{{ user }}"
      key: "{{ sshkey }}"
      state: present

  - name: "Enable ssh key authentication on the host"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: "PasswordAuthentication no"
      state: present
      backup: yes
    become: yes
    notify:
      - restart ssh

  - name: "Disable root login"
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes
    become: yes
    notify:
      - restart ssh

  handlers:
  - include_tasks: /handlers/handler.yaml