apiVersion: v1
kind: Namespace
metadata:
  name: cloudru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: cloudru
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /id
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /hostname
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 10
        env:
          - name: UUID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: cloudru
spec:
  selector:
    app: app
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000